name:
  - "Bertelsmeyer Hall, Rolla, MO"
  - "Butler-Carlton Hall, Rolla, MO"
  - "Castleman Hall, Rolla, MO"
  - "Computer Science Building, Rolla, MO"
  - "Emerson Hall, Rolla, MO"
  - "Engineering Management Building, Rolla, MO"
  - "Applied Research Center, Rolla, MO"
  - "Fulton Hall, Rolla, MO"
  - "Harris Hall, Rolla, MO"
  - "Innovation Lab, Rolla, MO"
  - "Physics Building, Rolla, MO"
  - "Humanities & Social Sciences, Rolla, MO"
  - "1400 North Bishop Avenue, Rolla, MO" # V.H. McNutt Hall
  - "Norwood Hall, Rolla, MO"
  - "Parker Hall, Rolla, MO"
  - "Rolla Building, Rolla, MO"
  - "Schrenk Hall, Rolla, MO"
  - "Toomey Hall, Rolla, MO"
  - "Straumanis-James Hall, Rolla, MO"
  - "Interdisciplinary Engineering Building, Rolla, MO"
  - "Curtis Laws-Wilson Library, Rolla, MO"